# Generated by Django 4.0.5 on 2022-06-03 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('num_pagine', models.CharField(max_length=250)),
                ('editorial', models.CharField(max_length=250)),
                ('isbn', models.CharField(max_length=250)),
            ],
        ),
    ]
