# Generated by Django 4.0.5 on 2022-06-03 00:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ejemplares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('apellido', models.CharField(max_length=250)),
                ('direccion', models.CharField(max_length=250)),
                ('telefono', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Prestar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_dev', models.DateField(default=django.utils.timezone.now)),
                ('fecha_pres', models.DateField(default=django.utils.timezone.now)),
                ('ejemplares', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ejemplares.ejemplares')),
                ('usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestar.usuarios')),
            ],
        ),
    ]
